# Generated by Django 4.2.10 on 2024-02-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='link'),
        ),
    ]
